#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

YELLOW='\033[1;30m'
echo -e "${YELLOW} Green Colored Statement"

echo "/************************************************/"
echo "/****** RUNNING prettier on staged files *******/"
echo "/***********************************************/"

git-format-staged -f 'prettier --ignore-unknown --stdin --stdin-filepath "{}"' .
